# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(default='static/demo/image/headers/9.jpg', upload_to='static/demo/image/headers/', verbose_name='用户头像'),
        ),
    ]
