# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_user_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='用户密码'),
        ),
    ]
